name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/joshleblanc/all-things-zerg/site:$(date +%s)
    - name: Login to registry
      run: docker login docker.pkg.github.com --username joshleblanc --password ${{ secrets.githubToken }}
    - name: Publish
      run: docker push docker.pkg.github.com/joshleblanc/all-things-zerg/site:$(date +%s)
